Homework-2
Maja1rus/pokemon-game pull request #1
Opened 2021-09-09 02:17 UTC by Maja1rus

Выполненное второе домашнее задание!

2021-09-09 09:49 UTC, ZarMarathon requested changes
Жду доработок!)

2021-09-09 09:49 UTC, ZarMarathon commented on src/App.js
> +// console.log(styleBg);
удали комменты

2021-09-09 09:49 UTC, ZarMarathon commented on src/App.js
> +            <Header
поправь форматирование

2021-09-09 09:49 UTC, ZarMarathon commented on src/App.js
> +                colorBg
Прочитай дз еще раз, выполнено не так, как задумано было)

2021-09-09 17:30 UTC, Maja1rus commented on src/App.js
> +                colorBg
Видимо не совсем понимаю, как правильно реализовать передачу стиля фона, можете привести пример?

2021-09-09 19:24 UTC, ZarMarathon approved these changes
Есть небольшие замечания, поправь их)
Ставлю заочный аппрув)

Как тебе в целом урок? Всё ли понятно?

![Approve](http://reactmarathon-api.herokuapp.com/assets/approve.png)

2021-09-09 19:24 UTC, ZarMarathon commented on src/components/Layout/Layout.jsx
> +    const styleRoot = imgBg ? {background: `url(${imgBg})`} : {background: `${colorBg}`}
Задача конечно решена верно, но оно очень узкое, проблема этого решения в том что если тебе придет и цвет и фон, то ты выберешь только фон игнорируя цвет.
Подумай как переделать так чтобы это решение было универсальным и оба свойства могли быть добавлены)

2021-09-10 11:09 UTC, Maja1rus commented on src/components/Layout/Layout.jsx
> +    const styleRoot = imgBg ? {background: `url(${imgBg})`} : {background: `${colorBg}`}
Посмотрел решение у вас в новом уроке, думаю сам бы пока ещё до такого не догадался, ну и плюс я ориентировался просто на background не подумав, что цвет или картинка будут друг дурга заменять. Но сейчас понял что тут лучше использовать backgroundImage и backgroundColor. В любом случаи спасибо, и за обратную связь тоже спасибо)

2021-09-10 15:46 UTC, merged